Ensure secondary concurrent executions of Gantry are not terminated when the first execution terminates, e.g. when doing parallel deployments.

diff --git a/gantry b/gantry
--- a/gantry
+++ b/gantry
@@ -2,13 +2,11 @@
 GANTRY_IMAGE=nlnetlabs/gantry:latest
 GANTRY_BIND_MOUNT_HOST_DIR=/tmp/gantry
 GANTRY_BIND_MOUNT_GUEST_DIR=/tmp/gantry
-SHELL_MODE=0
+
+ALREADY_RUNNING=0
+docker container inspect gantry &>/dev/null && ALREADY_RUNNING=1
 
 case $1 in
-    shell)
-        SHELL_MODE=1 && shift
-        ;;
-
     upgrade)
         docker pull ${GANTRY_IMAGE} && shift
         exit 0
@@ -16,6 +14,10 @@ case $1 in
 
     --data-dir)
         if [[ $# -ge 2 || ! -d "${GANTRY_BIND_MOUNT_HOST_DIR}" ]]; then
+            if [ ${ALREADY_RUNNING} -eq 1 ]; then
+                echo >&2 "ERROR: --data-dir cannot be changed when Gantry is already running..."
+                exit 1
+            fi
             GANTRY_BIND_MOUNT_HOST_DIR="$(realpath $2)" && shift 2
             echo "Data directory to use on host: ${GANTRY_BIND_MOUNT_HOST_DIR}"
         else
@@ -26,23 +28,12 @@ esac
 
 COMMON_ARGS="-it -e DEBUG -e ANSIBLE_DEBUG -e GANTRY_BIND_MOUNT_HOST_DIR=${GANTRY_BIND_MOUNT_HOST_DIR} -e GANTRY_BIND_MOUNT_GUEST_DIR=${GANTRY_BIND_MOUNT_GUEST_DIR}"
 
-docker container inspect gantry &>/dev/null
-if [ $? -eq 0 ]; then
+if [ ${ALREADY_RUNNING} -eq 1 ]; then
     echo "Connecting to existing instance of gantry.."
     echo
-    CMD="/opt/nlnetlabs/gantry/cli"
-    [ "${SHELL_MODE}" -eq 1 ] && CMD=/bin/bash
-    docker exec ${COMMON_ARGS} gantry ${CMD} $*
+    docker exec ${COMMON_ARGS} gantry /opt/nlnetlabs/gantry/cli $*
 else
-    ENTRYPOINT_OVERRIDE=""
-    EXTRA_ARGS=""
-    if [ "${SHELL_MODE}" -eq 1 ]; then
-        ENTRYPOINT_OVERRIDE="--entrypoint=/bin/bash"
-        while [ $# -gt 0 ]; do shift; done
-        echo 'Entering shell mode..'
-        echo
-    fi
-    docker run ${COMMON_ARGS} ${ENTRYPOINT_OVERRIDE} \
+    docker run ${COMMON_ARGS} \
         --name gantry \
         --env-file gantry.cfg \
         --volume gantry:/root/.docker/machine \
